### ISSUE TITLE
`test_readwrite` fails for python3 with pickling error

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/klepto#43]
```
>$ python test_readwrite.py 
Traceback (most recent call last):
  File "test_readwrite.py", line 122, in <module>
    check_basic(archive)
  File "test_readwrite.py", line 79, in check_basic
    d['c'] = min
  File "/Users/mmckerns/lib/python3.5/site-packages/klepto-0.1.2.dev0-py3.5.egg/klepto/_archives.py", line 332, in __setitem__
    self._store(key, value, input=False) # input=True also stores input
  File "/Users/mmckerns/lib/python3.5/site-packages/klepto-0.1.2.dev0-py3.5.egg/klepto/_archives.py", line 539, in _store
    _pickle.dump(value, _file, compress=compression)
  File "/Users/mmckerns/lib/python3.5/site-packages/klepto-0.1.2.dev0-py3.5.egg/klepto/_pickle.py", line 386, in dump
    pickler.dump(value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/Users/mmckerns/lib/python3.5/site-packages/klepto-0.1.2.dev0-py3.5.egg/klepto/_pickle.py", line 264, in save
    return Pickler.save(self, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.5.dev0-py3.5.egg/dill/dill.py", line 915, in save_builtin_method
    _recurse = pickler._recurse
AttributeError: 'NumpyPickler' object has no attribute '_recurse'
```

**Comment by mmckerns** [comment]
Fixed by https://github.com/uqfoundation/dill/commit/23a699282ed634087df0c758a32ea030c08fdfce
