### ISSUE TITLE
can't ignore parameter with JSON pickler

### ISSUE THREAD

**Issue by jscheithe** [uqfoundation/klepto#59]
Hi all, 
thanks for the great work on this package.

I'm trying to ignore a function argument, using JSON pickler.
The reason I want to use JSON is, that I can sort dicts by their keys and get unique representations.

Thanks for your help!

```
from klepto import lru_cache as memoize
from klepto.keymaps import picklemap

pickler = picklemap(serializer='json')

@memoize(keymap=pickler, ignore=('para1',))
def my_func(para1, para2):
    print(para1, para2)

my_func('foo', 'bar')
```
```
Traceback (most recent call last):

  File "<ipython-input-9-7cd04fe87d77>", line 13, in <module>
    my_func('foo', 'bar')

  File ...\envs\p36\lib\site-packages\klepto\_cache.py", line 723, in wrapper
    key = keymap(*_args, **_kwds)

  File "...\envs\p36\lib\site-packages\klepto\keymaps.py", line 138, in __call__
    return self.encode(*args, **kwds)

  File "...\envs\p36\lib\site-packages\klepto\keymaps.py", line 323, in encode
    return pickle(keymap.encode(self, *args, **kwds), serializer=self.__type__, **self._config) # separator=(',',':') for json

  File "...\envs\p36\lib\site-packages\klepto\crypto.py", line 122, in pickle
    return serializer.dumps(object) #XXX: better alternative behavior?

  File "...\envs\p36\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)

  File "...\envs\p36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "...\envs\p36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)

  File "...\envs\p36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)

TypeError: Object of type '_Null' is not JSON serializable
```

**Comment by mmckerns** [comment]
I hesitate to start messing with pickling objects that can't be serialized with `json`... however, maybe I might make a special exception for the `_Null` object.  Hmm.

I have added `jsonpickle` as a potential serializer in 332736353d20fffa2669864d63bc5c76da2f5d4e.  Is that sufficient for your intended use?
You'd just do `pickler = picklemap(serializer='jsonpickle')` instead of what you have above.

If this works for you, close this ticket.  If not, let me know, and I'll think about what to do about making `_Null` serializable with `json`.

**Comment by mmckerns** [comment]
I'm going to close this.  If `jsonpickle` isn't sufficient, please reopen and comment.
