### ISSUE TITLE
update for changes to h5py string handling

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/klepto#88]
tests/test_hdf.py (fails for h5py-3.0.0):
```
682Traceback (most recent call last):
683  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klepto-0.2.1.dev0-py3.6.egg/klepto/safe.py", line 772, in wrapper
684    result = cache[key]
685KeyError: "((), {'x': 2, 'y': 2})"
686
687During handling of the above exception, another exception occurred:
688
689Traceback (most recent call last):
690  File "tests/test_hdf.py", line 110, in <module>
691    test_combinations()
692  File "tests/test_hdf.py", line 99, in test_combinations
693    func = [_test_cache(cache, mapper) for cache in archives]
694  File "tests/test_hdf.py", line 99, in <listcomp>
695    func = [_test_cache(cache, mapper) for cache in archives]
696  File "tests/test_hdf.py", line 23, in _test_cache
697    r = f(choice(domain), choice(domain))
698  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klepto-0.2.1.dev0-py3.6.egg/klepto/safe.py", line 810, in wrapper
699    if cache.archived(): cache.dump(key)
700  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klepto-0.2.1.dev0-py3.6.egg/klepto/_archives.py", line 182, in dump
701    self.archive.update({arg:self.__getitem__(arg)})
702  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klepto-0.2.1.dev0-py3.6.egg/klepto/_archives.py", line 2337, in update
703    self.__save__(memo, new=False)
704  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klepto-0.2.1.dev0-py3.6.egg/klepto/_archives.py", line 2124, in __save__
705    _f[_k] = self._dumpval(v)
706  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/h5py/_hl/group.py", line 421, in __setitem__
707    ds = self.create_dataset(None, data=obj)
708  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/h5py/_hl/group.py", line 153, in create_dataset
709    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
710  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 137, in make_new_dset
711    dset_id.write(h5s.ALL, h5s.ALL, data)
712  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
713  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
714  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
715  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
716  File "h5py/_conv.pyx", line 443, in h5py._conv.str2vlen
717  File "h5py/_conv.pyx", line 94, in h5py._conv.generic_converter
718  File "h5py/_conv.pyx", line 255, in h5py._conv.conv_str2vlen
719ValueError: VLEN strings do not support embedded NULLs
```

**Comment by mmckerns** [comment]
See also: https://github.com/uqfoundation/klepto/commit/43afb6abaf261205a64a070f8e6bc8a1ff0cc366.

Reference page for the redesign of strings in h5py:
https://github.com/h5py/h5py/blob/e14f47a81d80af929c405d86dabc26444771185d/docs/strings.rst

**Comment by mmckerns** [comment]
See 0cd3baaf36b45d4a8dfefd32ea248d7ad9f958c9: the above error is thrown only when `serialized=True` and `meta=False`.

**Comment by mmckerns** [comment]
All sorts of keys work (see further below).
Oddly, dumping two ints works...
```
>>> f(4, 3)
15
>>> f.dump()
>>> ar
hdf_archive('memo.hdf5', {"((), {'x': 4, 'y': 3})": 15}, cached=True)
>>> ar.archive
hdf_archive('memo.hdf5', {"((), {'x': 4, 'y': 3})": 15}, cached=False)
>>> 
```
however, if either is a float, it fails.

Hmm... and dumping directly from the dict interface works for non-ints.
```
>>> ar = f.__cache__()
>>> ar["((), {'x': 4, 'y': 3})"] = 15
>>> ar.dump()
>>> ar.clear()
>>> ar.sync(clear=True)
>>> 
>>> ar["((), {'x': 4.0, 'y': 3})"] = 15
>>> ar.dump()
>>> ar.clear()
>>> ar.sync(clear=True)
>>> ar["((), {'x': 4.0, 'y': 3.0})"] = 15
>>> ar.dump()
>>> ar.clear()
>>> ar.sync(clear=True)
```

Interesting... it's actually the return value that's the issue:
```
>>> ar[f.key(4.0, 3)] = 15
>>> ar.dump()
>>> ar.clear()
>>> ar.sync(clear=True)
>>>
``` 
Ints are ok, but at least floats and string-types fail (i.e. `'15.0'`, `b'15.0'`)

**Comment by mmckerns** [comment]
The first succeeds, while the latter two fail.
```
>>> ar.archive._dumpval(15)
[b'\x80\x03K\x0f.']
>>> ar.archive._dumpval(15.0)
[b'\x80\x03G@.\x00\x00\x00\x00\x00\x00.']
>>> ar.archive._dumpval('15')
[b'\x80\x03X\x02\x00\x00\x0015q\x00.']
```
Note also that `meta=True` succeeds in all cases -- the impact being that there's no enclosing list.
